server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: DisProLog
  static_configs:
  - targets:
      - localhost
    labels:
      job: DisProLog
      __path__: "C:\\Program Files (x86)\\QualiSystems\\CloudShell\\Server\\JsonLogs\\DisPro.json.log"
- job_name: TeamServerLog
  static_configs:
  - targets:
      - localhost
    labels:
      job: TeamServerLog
      __path__: "C:\\Program Files (x86)\\QualiSystems\\TestShell\\ExecutionServer\\JsonLogs\\TeamServer.Service.json.log"
